name: EAS Build and Submit

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Submit to Google Play
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Create Google Service Account file
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' > google-play-service-account.json

      - name: Build and Submit AAB
        run: |
          eas build --platform android --profile production --non-interactive --auto-submit

      - name: Cleanup
        if: always()
        run: rm -f google-play-service-account.json
